=== shreyal009/XML_tutorial/xmlclasswork/XMLassignment/bookChar.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="book">
<xs:complexType>
	<xs:sequence>
		<xs:element ref="title"/>
		<xs:element ref="author"/>
		<xs:element ref="character" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
<xs:attribute name="isbn" type="isbnType" use="required"/>
</xs:complexType>
</xs:element>

<xs:simpleType name="isbnType">
	<xs:restriction base="xs:int">
		<xs:totalDigits value="10"/>
	</xs:restriction>
</xs:simpleType>

<xs:element name="character">
<xs:complexType>
	<xs:sequence>
		<xs:element ref="name"/>
		<xs:element ref="since"/>
		<xs:element ref="friend-of"/>
		<xs:element ref="qualification"/>
	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="title" type="xs:string"/>
<xs:element name="author" type="xs:string"/>
<xs:element name="name" type="xs:string"/>
<xs:element name="since" type="xs:date"/>
<xs:element name="friend-of" type="xs:string"/>
<xs:element name="qualification" type="xs:string"/>
</xs:schema>

=== shreyal009/XML_tutorial/xmlclasswork/XMLassignment/bookChar.xml
<?xml version="1.0" encoding="UTF-8"?>

<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bookChar.xsd" isbn="9766332625">
 <title>  Being a Dog Is a Full-Time Job </title>
 <author>Charles M. Schulz</author>
 <character>
	  <name>Snoopy</name>
	  <friend-of>Peppermint Patty</friend-of>
	  <since>1950-10-04</since>
	  <qualification>extroverted beagle</qualification>
 </character>
 <character>
	  <name>Peppermint Patty</name>
	  <since>1966-08-22</since>
	  <friend-of>xyz</friend-of>
	  <qualification>bold, brash and tomboyish</qualification>
 </character>
</book>
