=== shreyal009/XML_tutorial/XML/chapter.dtd
<!ELEMENT chapter (chapter_no,title,content)>
<!ELEMENT chapter_no (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT content (paragraph+|poem+)>
<!ELEMENT paragraph (poet+)>
<!ELEMENT poet (#PCDATA)>
<!ELEMENT poem (line+)>
<!ELEMENT line (#PCDATA)>

=== shreyal009/XML_tutorial/XML/chapter-4.xml
<?xml version="1.0"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<chapter>
<chapter_no>1</chapter_no>
<title>Home They Brought</title>
<content>
<poem>
<line>Home they brought her warrior dead</line>
<line>She never weeped nor uttered a cry</line>
<line>All her maidens watching said</line>
<line>She must weep or she will die</line>
</poem>
</content>
</chapter>
