=== shreyal009/XML_tutorial/xmlclasswork/chapter.dtd
<!ELEMENT chapter (title,content,chapterno)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT content (paragraphs|poems)>
<!ELEMENT poems (line)+>
<!ELEMENT line (#PCDATA)>
<!ELEMENT  paragraphs (index)>
<!ELEMENT index (#PCDATA)>
<!ELEMENT chapterno (#PCDATA)>

=== shreyal009/XML_tutorial/xmlclasswork/chapter.xml
<?xml version="1.0"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<chapter>
<title>XML programming</title>
<content>
<paragraphs>
<index>18</index>
</paragraphs>
<poems>
<line>its linux</line>
<line>linux shell script</line>
</poems>
</content>
<chapterno>1</chapterno>
</chapter>
